spring.application.name=product

spring.datasource.url=jdbc:mysql://localhost:3307/productdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# Jackson
spring.jackson.default-property-inclusion=non_null

# Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.url=/v3/api-docs
springdoc.override-with-generic-response=false
server.forward-headers-strategy=framework
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config

spring.devtools.restart.log-condition-evaluation-delta=false

# File upload
app.upload.dir=uploads/products
app.base-url=http://localhost:8080
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# GZIP Auto Compression for high performance Import / Export
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/pdf
server.compression.min-response-size=1024

# Redis Config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=true

# Mailtrap SMTP Config
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=dcaf579ecfc604
spring.mail.password=66136fafd4dc29
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.mail.from=inventory@hepl-product.com

# Daily Sales & Inventory Report Scheduler
app.scheduler.sales-report.cron=0 59 23 * * *
app.scheduler.sales-report.to=admin@hepl-product.com
app.scheduler.sales-report.low-stock-threshold=10